version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:rafael@mongo:27017/
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rafael
      - MONGO_INITDB_ROOT_PASSWORD=senha123
      - MONGO_INITDB_DATABASE=teste
